spring:
    cloud:
        gateway:
            routes: # 路由配置
                - id: soybean-auth
                  uri: lb://soybean-auth
                  predicates: # 断言
                    - Path=/auth/**
                - id: soybean-upms
                  uri: lb://soybean-upms
                  predicates: # 断言
                    - name: Path
                      args:
                        patterns:
                          - /systemManage/menu/**
                          - /systemManage/role/**
                          - /systemManage/user/**
                          - /systemManage/storageConfig/**
# 放行URL配置
security:
  permit-all:
    urls:
      - /systemManage/menu/static
      - /auth/**